### PR TITLE
This should be a lot more robust

### PR DESCRIPTION
**Pull request by dhoerl**
Martin,

So I added a Xcode project, and added some few new test. I had to comment some out as you will need to do work in the engineering to double method - see what I did in my project (essentially return NaN if the input is garbage).

David

### CODE REVIEW

**Comment by martinmoene** [comment]
Hi David,

My first concern with the changed `to_engineering_string()` is that it relies on C++11-specific utilities for floating point, such as `fpclassify()` and `signbit()`. Also, if at all possible, I like to be able to use the code even with Visual C++ 6 (!). For someone not very versed in floating point intricacies, it looks rather complex and that made me wonder if using another algorithm might prevent these complexities. I found a somewhat different approach on StackOverflow in Python and converted that to a new `to_engineering_string()` in C++. It works nicely and passes the tests.

So as a result, I will not merge this pull request.

Thanks for your contributions.

Martin

**Comment by dhoerl** [comment]
1) You should add an attribution of the StackOverflow post to your README - I'm curious to see what the author did.

2) It would be great if you would at least modify your tests to use the macros and reformatted test lines, as I did add several more, and in the future if I get additional feedback we could share each others test scripts.

**Comment by martinmoene** [comment]
Ad 1) Thanks for pointing out to do a better job it this.

**Comment by martinmoene** [comment]
Ad 2) I'll go through this too somewhat later.

Update 1 July 2013

I updated `test_eng_format.cpp` to use my lest test framework and made changes to allow for testing of C versions of the functions. Added macro TEST_C_VERSION_BY_DH to `select to_engineering_string_units()`.

Also renamed and expanded the tests. With the addition of your tests and several new ones I found some errors in my version of `to_engineering_string()` and one error in `step_engineering_string()`.

Failing tests (g++ 4.8.1):
- line.146 formats as '-1000.000e-27', should be "-1.00000 y"
- line.159 formats as '100.0 z', should be "100 z"

**Pull request closed without merging**
